export {default as userRoutes} from './user'
export {default as authRoutes} from './auth'
export {default as categoryRoutes} from './category'
export {default as productsRoutes} from './product'
export {default as bondingAssociatedRoutes} from './bondingAssociated'
export {default as shippingRoutes} from './shipping'